version: '3.1'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars_db

volumes:
  dbbase: